env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    conf: "ENCRYPTED[a0816c0b2683df8ba22e8a4edf5293cf009897d403086d46924601d366cb5cd73d29cc1050608d83ada545200db850e2]"

task:
  name: master
  timeout_in: 2h
  container:
    image: dopaemon/bionic:latest
    cpu: 8
    memory: 8G

  ubuntu_script:
    - rm -rf *
    - sudo apt-get update
    - sudo apt-get install -y ccache rclone mkbootimg img2simg jq sudo wget xz-utils
  halium_script:
    - git clone https://github.com/UbPorts-On7xelte/SamSung-Exynos7870.git /tmp/ci/halium
    - cd /tmp/ci/halium
    - ./cirrusci.sh
